version: "3.7"
services:
  mariadb:
    image: mariadb:latest
    ports:
    - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - mariadb_dv:/var/lib/mysql
  postgres:
    image: postgres:latest
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_dv:/var/lib/postgresql/data
volumes:
  mariadb_dv:
  postgres_dv:
