"""recreate all.

Revision ID: e5afdddca964
Revises: 
Create Date: 2020-03-19 23:06:00.605820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5afdddca964'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', 'type_')
    )
    op.create_table('entity_attribute',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_attribute_value',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('attribute_id', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['entity_id', 'entity_type'], ['entity.id', 'entity.type_'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('entity_id', 'entity_type', 'attribute_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity_attribute_value')
    op.drop_table('contact')
    op.drop_table('entity_attribute')
    op.drop_table('entity')
    # ### end Alembic commands ###
